"""Synthetic data validation agent.

Reviews synthetic samples generated by gen_all_datasets.py for quality
and flags low-quality/off-topic samples before training.
"""

import json
import logging
import random
from pathlib import Path
from typing import Optional, Dict, Any, List
from datetime import datetime

logger = logging.getLogger(__name__)


class SyntheticValidator:
    """Validates synthetically generated prompt injection samples."""

    # Categories in synthetic data
    CATEGORIES = [
        "D1", "D2", "D3", "D4", "D5", "D6", "D7", "D8",  # Direct
        "E1", "E2",  # Evasion
        "C1",  # Combination
        "O1",  # Out-of-scope
        "P1",  # Prompt leakage
    ]

    def __init__(self, data_dir: str = "data"):
        self.data_dir = Path(data_dir)
        self.holdout_path = self.data_dir / "holdout" / "malicious_holdout.jsonl"

    def load_synthetic_samples(self) -> Dict[str, List[Dict[str, Any]]]:
        """Load synthetic samples grouped by category.

        Returns:
            Dict mapping category -> list of sample dicts
        """
        if not self.holdout_path.exists():
            logger.warning(f"Holdout file not found: {self.holdout_path}")
            return {}

        samples_by_cat = {cat: [] for cat in self.CATEGORIES}

        try:
            with open(self.holdout_path) as f:
                for line in f:
                    if not line.strip():
                        continue
                    sample = json.loads(line)
                    category = sample.get("category", "?")
                    if category in samples_by_cat:
                        samples_by_cat[category].append(sample)
        except Exception as e:
            logger.error(f"Error loading holdout: {e}")
            return {}

        return samples_by_cat

    def sample_per_category(self, samples_by_cat: Dict[str, List[Dict[str, Any]]], percentage: float = 0.05) -> Dict[str, List[Dict[str, Any]]]:
        """Sample N% of samples from each category for review.

        Args:
            samples_by_cat: Category -> sample list mapping
            percentage: Sampling percentage (default 5%)

        Returns:
            Dict mapping category -> sampled list
        """
        sampled = {}

        for category, samples in samples_by_cat.items():
            if not samples:
                continue

            sample_size = max(1, int(len(samples) * percentage))
            sampled[category] = random.sample(samples, min(sample_size, len(samples)))

        return sampled

    def flag_low_quality(self, samples_by_cat: Dict[str, List[Dict[str, Any]]]) -> Dict[str, List[Dict[str, Any]]]:
        """Identify low-quality samples that should be removed.

        Flags:
        - Too short (< 20 chars)
        - Not actually injections (looks like benign prompt)
        - Off-topic/noisy

        Args:
            samples_by_cat: Category -> sample list

        Returns:
            Dict mapping category -> list of flagged samples
        """
        flagged = {}

        for category, samples in samples_by_cat.items():
            category_flagged = []

            for sample in samples:
                text = sample.get("text", "").strip()
                reason = None

                # Too short
                if len(text) < 20:
                    reason = "too_short"

                # Likely not an injection attempt
                elif not any(marker in text.lower() for marker in [
                    "ignore", "forget", "forget previous", "disregard", "override",
                    "act as", "pretend", "role-play", "jailbreak", "bypass",
                    "system prompt", "instructions", "secret", "hidden"
                ]):
                    # Heuristic: if it doesn't contain common injection markers, flag it
                    if category.startswith("D") or category.startswith("E"):
                        reason = "no_injection_markers"

                if reason:
                    sample["flag_reason"] = reason
                    category_flagged.append(sample)

            if category_flagged:
                flagged[category] = category_flagged

        return flagged

    def compile_validation_report(self) -> Optional[Dict[str, Any]]:
        """Compile full synthetic data validation report.

        Returns:
            Validation report dict, or None if no holdout file
        """
        all_samples = self.load_synthetic_samples()
        if not all_samples:
            return None

        total_count = sum(len(s) for s in all_samples.values())
        if total_count == 0:
            return None

        sampled = self.sample_per_category(all_samples)
        flagged = self.flag_low_quality(sampled)

        total_flagged = sum(len(f) for f in flagged.values())

        return {
            "timestamp": datetime.now().isoformat(),
            "total_samples": total_count,
            "samples_reviewed": sum(len(s) for s in sampled.values()),
            "flagged_count": total_flagged,
            "flagged_by_category": {cat: len(flags) for cat, flags in flagged.items()},
            "flagged_samples": flagged,
            "recommendation": "remove" if total_flagged > 0 else "keep",
        }

    def format_message(self) -> str:
        """Format validation results for iMessage.

        Returns:
            Summary message for user decision
        """
        report = self.compile_validation_report()
        if not report:
            return "ℹ️  Synthetic data validation: no holdout file found. Skipping review."

        if report["flagged_count"] == 0:
            return f"✅ Synthetic data OK: {report['total_samples']} samples, 0 flagged"

        lines = [f"⚠️  Synthetic data review: {report['flagged_count']} sample(s) flagged"]
        for cat, count in report["flagged_by_category"].items():
            if count > 0:
                lines.append(f"  {cat}: {count} flagged")

        lines.append("\nRemove flagged samples before training? Reply: yes remove | keep all")
        return "\n".join(lines)

    def write_report(self, report_dir: str = "data/approval_queue") -> Optional[str]:
        """Write validation report to disk.

        Args:
            report_dir: Directory to write reports to

        Returns:
            Path to written report, or None if no flagged samples
        """
        report = self.compile_validation_report()
        if not report:
            return None

        report_dir = Path(report_dir)
        report_dir.mkdir(parents=True, exist_ok=True)

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        report_path = report_dir / f"synthetic_validation_{timestamp}.json"

        try:
            with open(report_path, "w") as f:
                json.dump(report, f, indent=2)
            logger.info(f"Wrote validation report to {report_path}")
            return str(report_path)
        except Exception as e:
            logger.error(f"Error writing report: {e}")
            return None

    def remove_flagged_samples(self) -> bool:
        """Remove flagged samples from holdout file.

        Returns:
            True if removal succeeded
        """
        report = self.compile_validation_report()
        if not report or report["flagged_count"] == 0:
            logger.info("No flagged samples to remove")
            return True

        flagged_ids = set()
        for flags in report["flagged_samples"].values():
            for sample in flags:
                # Use text as unique ID (in production would use proper IDs)
                flagged_ids.add(sample.get("text", ""))

        try:
            kept = []
            with open(self.holdout_path) as f:
                for line in f:
                    if not line.strip():
                        continue
                    sample = json.loads(line)
                    if sample.get("text", "") not in flagged_ids:
                        kept.append(sample)

            with open(self.holdout_path, "w") as f:
                for sample in kept:
                    f.write(json.dumps(sample) + "\n")

            logger.info(f"Removed {len(flagged_ids)} flagged samples")
            return True
        except Exception as e:
            logger.error(f"Error removing flagged samples: {e}")
            return False

    def handle_user_response(self, user_response: str) -> tuple[bool, int, str]:
        """Act on the user's reply to a synthetic-validation alert.

        The alert asks the user to reply "yes remove" (drop flagged samples)
        or "keep all" (leave them). Mirrors the deploy/quarantine reply pattern
        so the orchestrator can execute the decision.

        Args:
            user_response: e.g. "yes remove" or "keep all"

        Returns:
            Tuple of (acted, num_removed, message) where ``acted`` is True if a
            valid decision was handled, ``num_removed`` is how many samples were
            dropped, and ``message`` is the iMessage to send back.
        """
        response = user_response.lower().strip()

        if "remove" in response or response in ("yes", "y"):
            # Capture the flagged count before removal (removal returns bool).
            report = self.compile_validation_report()
            flagged = report.get("flagged_count", 0) if report else 0
            if self.remove_flagged_samples():
                return True, flagged, f"✅ Removed {flagged} flagged sample(s)"
            return False, 0, "❌ Failed to remove flagged samples"

        if "keep" in response or response in ("no", "n"):
            return True, 0, "✅ Kept all samples; none removed"

        return False, 0, "❓ Reply: yes remove | keep all"
